kind: pipeline
name: default
steps:
  - name: publish
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: thomaswiener/docker-kubeval
      tags:
        - latest
        - 1.0.0
    when:
      branch:
        - main
