kind: pipeline
name: default
steps:
  - name: tags
    image: golang
    commands:
      - echo -n "latest,${DRONE_TAG}" > .tags
      - cat .tags

  - name: publish
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: thomaswiener/docker-kubeval

trigger:
  event:
    - tag