kind: pipeline
name: default
steps:
  - name: publish
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: thomaswiener/docker-kubeval
      auto_tag: true
      tags:
        - latest

trigger:
  event:
    - tag